name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, json, curl
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer test

    - name: Run code style check
      run: composer phpcs

    - name: Run static analysis
      run: composer phpstan
      if: matrix.php-versions == '8.1'

    - name: Generate coverage report
      run: composer test-coverage
      if: matrix.php-versions == '8.1'

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.php-versions == '8.1'
      with:
        file: ./coverage/clover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, json, curl

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run security check
      run: |
        if [ -f composer.lock ]; then
          composer audit
        fi